development:
  clients:
    default:
      uri: mongodb://localhost:27017/opennote_development
      options:
        server_selection_timeout: 5

test:
  clients:
    default:
      uri: mongodb://localhost:27017/opennote_test
      options:
        server_selection_timeout: 5

production:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] %>
      options:
        server_selection_timeout: 5 